version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
