repos:
  - repo: https://github.com/norwoodj/helm-docs
    rev: v1.7.0
    hooks:
      - id: helm-docs
        args:
          # Make the tool search for charts only under the `example-charts` directory
          - --chart-search-root=charts/s3sync-service

          # The `./` makes it relative to the chart-search-root set above
          - --template-files=./docs-template.md

          # Documentation output file, the path is relative to the chart repository
          - --output-file=../../docs/helm-charts.md
