aws_region: us-east-1
# upload_workers: 10
# checksum_workers: 10
watch_interval: 5m
s3_ops_retries: 10
sites:
- local_path: /Users/yevgeniy_valeyev/test-s3sync-service
  bucket: test-s3sync-service
  retire_deleted: true
  exclusions:
  - .[Dd][Ss]_[Ss]tore
  - .[Aa]pple[Dd]ouble
  - "[Tt]humbs.db"
