{{- if .Values.createRbac }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "s3sync.fullname" . }}
  labels:
    {{- include "s3sync.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    resourceNames:
      - "{{ include "s3sync.fullname" . }}"
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "s3sync.fullname" . }}
  labels:
    {{- include "s3sync.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "s3sync.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "s3sync.fullname" . }}
    namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "s3sync.serviceAccountName" . }}
  labels:
    {{- include "s3sync.labels" . | nindent 4 }}
{{- end }}
