upload_workers: 10
loglevel: debug
sites:
- local_path: /some/local/path
  bucket: test-s3sync-service
  retire_deleted: true
  exclusions:
    - .[Dd][Ss]_[Ss]tore
- local_path: /some/other/local/path
  bucket: some-s3-bucket
  exclusions:
    - .[Dd][Ss]_[Ss]tore
    - .[Aa]pple[Dd]ouble
    - "[Tt]humbs.db"
