name: hadolint

on:
  push:
    tags:
    branches:
      - master
  pull_request:

jobs:
  hadolint:
    name: hadolint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: Dockerfile
